# Generated by Django 6.0 on 2025-12-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_consume_date_alter_food_carbs_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='consume',
            name='quantity',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='carbs_goal_pct',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='fats_goal_pct',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='profile',
            name='protein_goal_pct',
            field=models.IntegerField(default=25),
        ),
    ]
