# Generated by Django 6.0 on 2025-12-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0003_consume_quantity_profile_carbs_goal_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activity_level',
            field=models.FloatField(choices=[(1.2, 'Sedentary'), (1.375, 'Lightly Active'), (1.55, 'Moderately Active'), (1.725, 'Very Active'), (1.9, 'Extra Active')], default=1.2),
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='goal_type',
            field=models.CharField(choices=[('loss', 'Weight Loss'), ('maintain', 'Maintenance'), ('gain', 'Weight Gain')], default='maintain', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.FloatField(default=170.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.FloatField(default=70.0),
        ),
    ]
